# Generated by Django 4.1 on 2024-09-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('username',)},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='driver',
            new_name='drivers',
        ),
    ]
